# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83eec2884a5b7c17cf74ea258fc1450e5d0626631e27da7edd2096e1044897d1be1d70f43e0ca714d7b65a1d14abc5cda7a02fc51f177141e463269a4ae029a0

test:
  secret_key_base: 39e78b234f41ac734291aea298f24608a9da16b5e91f459f5cd45b5534a6b455771860f1b74ddae5483e0bf7698cea5588ce512e40b601dede43c28c9794f985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
